### ISSUE TITLE
cookie怎么加？

### ISSUE THREAD

**Issue by fisher7757** [web-liuyang/uni-app-tools#1]
谢谢谢谢

**Comment by web-liuyang** [comment]
获取cookit值后可以加在 全局配置表 defaultData属性里面 ，但是建议不用cookie，使用token更为方便

**Comment by web-liuyang** [comment]
获取cookit值后可以加在 全局配置表 defaultData属性里面 ，但是建议不用cookie，使用token更为方便




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fisher7757"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 下午4:14
收件人:&nbsp;"web-liuyang/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[web-liuyang/uni-app] cookie怎么加？ (#1)





 
谢谢谢谢

**Comment by fisher7757** [comment]
好的，谢谢你
